### ISSUE TITLE
Unable to unzip compressed trained model

### ISSUE THREAD

**Issue by EloyRoura** [uthmri/Deep-Learning-MS-Segmentation#1]

**Comment by rgabr** [comment]
Dear Eloy,

Thank you for your interest in our work. We tested downloading,
uncompressing and running the model and it looks to run OK. We used 7-zip to
unzip the data. Please let me know if you can reproduce this with 7-zip.

Thank you,
Refaat

*Refaat Gabr, Ph.D.*

Assistant Professor

Department of Diagnostic and Interventional Imaging

McGovern Medical School
*UTHealth* | The University of Texas Health Science Center at Houston

6431 Fannin St | MSE R102D | Houston, TX 77030
713 500 7660 tel | 713 500 7684 fax

**Comment by EloyRoura** [comment]
Hello Refaat,

Thank you for your help. I succeed with the unzip just right after writing the post and that's why I deleted it.

Just for clarification, normal unzipping in linux would not make the work, and the same for Mac OS. The problem seemed to be about the buffer size of both native systems. However, The Unarchiver on Mac was the solution for me. I guess, 7-zip is also fine :)

KR,
Eloy

**Comment by rgabr** [comment]
Thank you, Eloy.
