### ISSUE TITLE
Different input size of trained model

### ISSUE THREAD

**Issue by isabellameds** [uthmri/Deep-Learning-MS-Segmentation#2]
Hi,
First of all, your work is great!
I would like to know if it's possible to use the trained model with just T1 and FL images? how?
Thanks in advance.

**Comment by rgabr** [comment]
> Hi,
> First of all, your work is great!
> I would like to know if it's possible to use the trained model with just T1 and FL images? how?
> Thanks in advance.

Thank you for your interest in our work. The model was trained on 4-channel input and this is the expected input. However, you will need to edit the code and train a new model to use two channels.
